### ISSUE TITLE
wrong order of log level activation 

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/micrologger#41]
Usually when you set a log level in a logger you configure the upper level of severity you want to emit. Say when you set a log level to `info` you want to see `info`, `warn` and `error` in our case. Though we implemented it the wrong way around. When you set `info` to the activation logger we emit `debug` and `info`. This should be corrected IMO. Am I correct with this? What other ideas do we have? 

/cc @giantswarm/team-firecracker-engineers @kopiczko

**Comment by anvddriesch** [comment]
IMO there is no reason why anyone would want to see `debug` and `info` but not `error`. Does this also mean that in case we ask for `error` we don't get `info` ?

**Comment by xh3b4sd** [comment]
I think right now we would get `info` as well when we set `error`. Because it is the wrong way around. We would not want to see info if we set `error`, because then we would only want to see `error` due to the severity hierarchy.
